module tb_full_adder;

reg A, B, Cin;
wire Sum, Carry;

full_adder uut (
    .a(A),
    .b(B),
    .c(Cin),
    .sum(Sum),
    .carry(Carry)
);

initial begin
    A = 0; B = 0; Cin = 0;
    #10;
    A = 0; B = 0; Cin = 1;
    #10;
    A = 0; B = 1; Cin = 0;
    #10;
    A = 0; B = 1; Cin = 1;
    #10;
    A = 1; B = 0; Cin = 0;
    #10;
    A = 1; B = 0; Cin = 1;
    #10;
    A = 1; B = 1; Cin = 0;
    #10;
    A = 1; B = 1; Cin = 1;
    #10;

    $finish;
end

endmodule
